const mongoose = require('mongoose');

const builder = mongoose.Schema({
    WoodSelection:{
        type:String,
        require:true
    },
    BodyConstruction:{
        type:String,
        require:true
    },
    BodyShapes:{
        type:String,
        require:true
    },
    BodyCurves:{
        type:String,
        require:true
    },
    BodyCavities:{
        type:String,
        require:true
    },
    BodyBinding:{
        type:String,
        require:true
    },
    NeckWoodSelection:{
        type:String,
        require:true
    },
    NeckConstruction:{
        type:String,
        require:true
    },
    Headstocks:{
        type:String,
        require:true
    },
    HeadstockAngles:{
        type:String,
        require: true
    },
    NeckTaping:{
        type:String,
        require:true
    },
    TrussRod:{
        type:String,
        require:true
    },
    NeckAssembly:{
        type:String,
        require:true,
    },
    FreatWoodSelection:{
        type:String,
        require:true
    },
    ScaleLenths:{
        type:String,
        require:true
    },
    FretNumbers:{
        type:String,
        require:true
    },
    FretboardRadius:{
        type:String,
        require:true
    },
    Inlays:{
        type:String,
        require:true
    },
    InlayMaterial:{
        type:String,
        require:true
    },
    BodyNeckBinding:{
        type:String,
        require:true
    },
    Fretwires:{
        type:String,
        require:true
    },
    Paint:{
        type:String,
        require:true
    },
    Finish:{
        type:String,
        require:true
    },
    CustomShopFinish:{
        type:String,
        require:true
    },
    TuningKeys:{
        type:String,
        require:true
    },
    Nut:{
        type:String,
        require:true
    },
    Bridges:{
        type:String,
        require:true
    },
    Pickups:{
        type:String,
        require:true
    },
    Potentiometers:{
        type:String,
        require:true
    },
    SelectorSwitches:{
        type:String,
        require:true
    },
    Knobs:{
        type:String,
        require:true 
    },
    OutputJacks:{
        type:String,
        require:true 
    },
    StrapPins:{
        type:String,
        require:true
    },
    Pickgaurds:{
        type:String,
        require:true
    },
    CustomGigBag:{
        type:String,
        require:true
    },
    CustomCase:{
        type:String,
        require:true
    },
    Strap:{
        type:String,
        require:true
    },
    picks:{
        type:String,
        require:true
    },
    fullName:{
        type:String,
        require:true
    },
    Phone:{
        type:String,
        require:true
    },
    email:{
        type:String,
        require:true
    },
    socialId:{
        type:String,
        require:true 
    },
    SpecialNote:{
        type:String,
        require:true
    },
    date:{
        type: Date,
        default: Date.now,
    }
})

module.exports = builder;
