const mongoose = require('mongoose');

const builder = mongoose.Schema({
    bodySelecion:{
        type:String,
        require:true
    },
    BodyConstruction:{
        type:String,
        require:true
    },
    BodyShapes:{
        type:String,
        require:true
    },
    BodyCurves:{
        type:String,
        require:true
    },
    BodyCavities:{
        type:String,
        require:true
    },
    BodyBinding:{
        type:String,
        require:true
    },
    NeckSelecion:{
        type:String,
        require:true
    },
    ScaleLenths:{
        type:String,
        require:true
    },
    FretNumbers:{
        type:String,
        require:true
    },
    FretboardRadius:{
        type:String,
        require:true
    },
    Inlays:{
        type:String,
        require:true
    },
    InlayMaterial:{
        type:String,
        require:true
    },
    BodyNeckBinding:{
        type:String,
        require:true
    },
    Fretwires:{
        type:String,
        require:true
    },
    Paint:{
        type:String,
        require:true
    },
    Finish:{
        type:String,
        require:true
    },
    CustomShopFInish:{
        type:String,
        require:true
    },
    TuningKeys:{
        type:String,
        require:true
    },
    Nut:{
        type:String,
        require:true
    },
    Bridges:{
        type:String,
        require:true
    },
    Pickups:{
        type:String,
        require:true
    },
    Potentiometers:{
        type:String,
        require:true
    },
    SelectorSwitches:{
        type:String,
        require:true
    },
    OutputJacks:{
        type:String,
        require:true
    },
    StrapPins:{
        type:String,
        require:true
    },
    Pickgaurds:{
        type:String,
        require:true
    },
    CustomGigBag:{
        type:String,
        require:true
    },
    CustomCase:{
        type:String,
        require:true
    },
    Strap:{
        type:String,
        require:true
    },
    Picks:{
        type:String,
        require:true
    },
    email:{
        type:String,
        require:true
    },
    
    description:String,
    pricing:Number,
    file:String,
    date:{
        type: Date,
        default: Date.now,
    }
})

module.exports = builder;
